//
//  TranslateRU.swift
//  WTFlower
//
//  Created by  Stepanok Ivan on 22.08.2021.
//

import Foundation


struct TranslateRU {
    func translate(input: String) -> String {
        switch input {
        case "pink primrose" : return "розовая примула"
        case "hard-leaved pocket orchid" : return "серебряная орхидея"
        case "canterbury bells" : return "колокольчик"
        case "sweet pea" : return "горох"
        case "english marigold" : return "календула"
        case "tiger lily" : return "тигровая лилия"
        case "moon orchid" : return "фаленопсис приятный"
        case "bird of paradise" : return "стрелиция королевская"
        case "monkshood" : return "борец клобучковый"
        case "globe thistle" : return "мордовник шароголовый"
        case "snapdragon" : return "львиный зев"
        case "colt's foot" : return "мать-и-мачеха"
        case "king protea" : return "протея артишоковая"
        case "spear thistle" : return "бодяк обыкновенный"
        case "yellow iris" : return "ирис ложноаировый"
        case "globe-flower" : return "купальница"
        case "purple coneflower" : return "эхинацея пурпурная"
        case "peruvian lily" : return "альстрёмерия"
        case "balloon flower" : return "ширококолокольчик"
        case "giant white arum lily" : return "зантедеския"
        case "fire lily" : return "глориоза роскошная"
        case "pincushion flower" : return "скабиоза"
        case "fritillary" : return "рябчик шахматный"
        case "red ginger" : return "имбирь аптечный"
        case "grape hyacinth" : return "гадючий лук"
        case "corn poppy" : return "мак самосейка"
        case "prince of wales feathers" : return "амарант"
        case "stemless gentian" : return "горечавка"
        case "artichoke" : return "артишок настоящий"
        case "sweet william" : return "гвоздика турецкая"
        case "carnation" : return "гвоздика садовая"
        case "garden phlox" : return "флокс"
        case "love in the mist" : return "чернушка дамасская"
        case "mexican aster" : return "космея дваждыперистая"
        case "alpine sea holly" : return "синеголовник альпийский"
        case "ruby-lipped cattleya" : return "каттлея"
        case "cape flower" : return "эрика (растение)"
        case "great masterwort" : return "астранция крупная"
        case "siam tulip" : return "куркума"
        case "lenten rose" : return "морозник восточный"
        case "barberton daisy" : return "гербера"
        case "daffodil" : return "нарцисс (растение)"
        case "sword lily" : return "шпажник болотный"
        case "poinsettia" : return "молочай красивейший"
        case "bolero deep blue" : return "эустома"
        case "wallflower" : return "желтушник"
        case "marigold" : return "бархатцы"
        case "buttercup" : return "лютик"
        case "oxeye daisy" : return "нивяник обыкновенный"
        case "common dandelion" : return "одуванчик"
        case "petunia" : return "петуния"
        case "wild pansy" : return "фиалка трёхцветная"
        case "primula" : return "первоцвет"
        case "sunflower" : return "подсолнечник"
        case "pelargonium" : return "пеларгония"
        case "bishop of llandaff" : return "георгина"
        case "gaura" : return "гаура линдхеймера"
        case "geranium" : return "герань"
        case "orange dahlia" : return "георгина"
        case "pink-yellow dahlia" : return "георгина"
        case "cautleya spicata" : return "бромелия"
        case "japanese anemone" : return "ветреница хубэйская"
        case "black-eyed susan" : return "рудбекия"
        case "silverbush" : return "вьюнок трёхцветный"
        case "californian poppy" : return "эшшольция калифорнийская"
        case "osteospermum" : return "остеоспермум"
        case "spring crocus" : return "шафран посевной"
        case "bearded iris" : return "ирис (растение)"
        case "windflower" : return "ветреница"
        case "tree poppy" : return "маковые"
        case "gazania" : return "газания"
        case "azalea" : return "азалия"
        case "water lily" : return "кувшинковые"
        case "rose" : return "роза"
        case "thorn apple" : return "дурман обыкновенный"
        case "morning glory" : return "ipomoea violacea"
        case "passion flower" : return "cтрастоцвет"
        case "lotus" : return "лотос"
        case "toad lily" : return "трициртис"
        case "anthurium" : return "антуриум"
        case "frangipani" : return "плюмерия"
        case "clematis" : return "ломонос"
        case "hibiscus" : return "гибискус"
        case "columbine" : return "водосбор (растение)"
        case "desert-rose" : return "адениум тучный"
        case "tree mallow" : return "хатьма древовидная"
        case "magnolia" : return "магнолия"
        case "cyclamen" : return "цикламен"
        case "watercress" : return "жеруха обыкновенная"
        case "canna lily" : return "канна (растение)"
        case "hippeastrum" : return "гиппеаструм"
        case "bee balm" : return "монарда"
        case "ball moss" : return "тилландсия уснеевидная"
        case "foxglove" : return "наперстянка"
        case "bougainvillea" : return "бугенвиллея"
        case "camellia" : return "камелия"
        case "mallow" : return "мальва"
        case "mexican petunia" : return "петуния"
        case "bromelia" : return "бромелия"
        case "blanket flower" : return "гайлардия"
        case "trumpet creeper" : return "кампсис укореняющийся"
        case "blackberry lily" : return "беламканда китайская"

        default:
            return "Oops"
        }
    }
}
